# Generated by Django 4.1.7 on 2023-03-02 08:48

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('health', 'health'), ('career', 'career'), ('parenting', 'parenting'), ('cooking', 'cooking'), ('shopping', 'shopping')], max_length=30, verbose_name='카테고리')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('slug', models.SlugField(allow_unicode=True, max_length=150, unique=True, verbose_name='제목별칭')),
                ('content', models.TextField(verbose_name='내용')),
                ('summary', models.TextField(verbose_name='요약')),
                ('hits', models.IntegerField(default=0, verbose_name='조회수')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
